[project]
name = "clarity-template"
requirements = []
costs_version = 1

[contracts.oracle-trait]
path = "contracts/oracle-trait.clar"
depends_on = []

[contracts.oracle]
path = "contracts/oracle.clar"
depends_on = ["nft-trait", "sip-010-trait-ft-standard", "oracle-trait"]

[contracts.sample-nft]
path = "contracts/samples/sample-nft.clar"
depends_on = ["nft-trait"]

[contracts.sample-ft]
path = "contracts/samples/sample-ft.clar"
depends_on = ["sip-010-trait-ft-standard"]

# EXTERNAL CONTRACTS
[contracts.sip-010-trait-ft-standard]
path = "contracts/external/sip-010-trait-ft-standard.clar"
depends_on = []


[contracts.nft-trait]
path = "contracts/external/sip-009-nft-trait-standard.clar"
depends_on = []
